                                                                                                                                                                                                                      

vikas_hsco

cd ../../home/vikas/HSco_development/
cd ../../home/vikas/HSco
source venv/bin/activate

cd Hsco/

python manage.py runserver 0.0.0.0:8000


ssh -i ~/ssh_hsco root@67.205.184.166
git pull
ctrl + x


RELOD SERVER:
sudo systemctl daemon-reload
sudo systemctl restart gunicorn.service nginx.service;



DB BACKUP MYSQL:
mysqldump -u root2 -p hsco_db > /home/vikas/hsco_db_backup/hsco_db_07_09_2020.sql;


PERMISSIONS:
sudo chmod -R 777 /var/www/


PRIMARY KEY RESET:
ALTER TABLE lead_management_lead AUTO_INCREMENT = 1
ALTER TABLE customer_app_lead_customer_details AUTO_INCREMENT = 1


DOWNLOAD FILE FROM SERVER:
scp -i ~/ssh_hsco root@139.59.76.87:/home/vikas/hsco_db_backup/hsco_db_04_07_2020.sql C:\sagar\hsco_db_04_07_2020.sql
scp -i sujeet.pem ubuntu@54.159.90.199:/home/ubuntu/eoxegen_backend/ E:/server_content/

RESTORE MYSQL DB
cd C:\mysql\bin
mysql -u root -p
mysql> source E:\hsco_db_19_06_2020.sql

UPLOAD FILE TO SERVER:
scp file.zip -i ~/ssh_hsco root@139.59.76.87:/home/vikas/hsco_db_backup



SHOW HIDDEN FILES IN LINUX:
ls -a


"del-cli-logos": "del-cli -f \"../static_local/img\"",




restore backup:
https://stackoverflow.com/questions/12425287/mysql-server-has-gone-away-when-importing-large-sql-file
https://stackoverflow.com/questions/24936314/fatal-error-maximum-execution-exceeded
